services:
  wedding-web:
    container_name: s-j-wedding
    build:
      context: .
      dockerfile: Dockerfile
    image: s-j-wedding:latest
    environment:
      HOST: 0.0.0.0
      PORT: 80
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: sj_wedding
    expose:
      - "80"
    depends_on:
      - mongo
    networks:
      - cloudflare_default
      - wedding_internal
    restart: unless-stopped

  mongo:
    container_name: s-j-wedding-mongo
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: sj_wedding
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - wedding_internal
    restart: unless-stopped

volumes:
  mongo_data:


networks:
  cloudflare_default:
    external: true
  wedding_internal:
    driver: bridge
