services:
  wedding-web:
    container_name: s-j-wedding
    build:
      context: .
      dockerfile: Dockerfile
    image: s-j-wedding:latest
    environment:
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-80}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-sj_wedding}
    expose:
      - "80"
    depends_on:
      - mongo
    networks:
      - cloudflare_default
    restart: unless-stopped
    extra_hosts:
          - "nombredelhostnas.tailscale.net:100.x.y.z" # Reemplaza con tu MagicDNS y IP de Tailscale


networks:
  cloudflare_default:
    external: true

